Repository Rosstail/JPDE2-french, pull requests merged in 2024-08, with the labels that each got.

#8 Update README.md
  README.md
Labels: documentation, Prochaine version (urgent), Review

#18 update
  french/battle/core_files/augmentation_locations.rpyc
  french/common.rpyc
  french/effects/outline_shader.rpyc
  french/exploratory/conv/outback_camp.rpyc
  french/exploratory/conv/red_command_01.rpyc
  french/maps/conv/evelyn_convs.rpyc
  french/maps/conv/jack_convs.rpyc
  french/maps/conv/maria_convs.rpyc
  french/maps/conv/penny_convs.rpyc
  french/maps/conv/ruby_convs.rpyc
  french/maps/conv/sienna_khan.rpyc
  french/maps/outback_01.rpyc
  french/maps/outback_02.rpyc
  french/music_room/music_room.rpyc
  french/options.rpy
  french/options.rpyc
  french/screens/dialogue_screens.rpyc
  french/screens/game_menu.rpyc
  french/screens/main_menu.rpyc
  french/screens/other_screens.rpyc
  french/screens/popup_screens.rpyc
  french/screens/preferences.rpyc
  french/screens/save_load.rpyc
  french/screens/scroll/history_screen.rpyc
  french/script.rpy
  french/script.rpyc
  french/script/credits.rpy
  french/script/credits.rpyc
  french/script/story/st_00.rpyc
  french/script/story/st_01.rpyc
  french/script/story/st_02.rpyc
  french/script/story/st_03.rpyc
  french/script/story/st_04.rpyc
  french/script/story/st_05.rpyc
  french/script/story/st_06.rpyc
  french/script/story/st_07.rpy
  french/script/story/st_07.rpyc
Labels: En cours, Prochaine version (urgent), Review

#21 R2-I20-Ajouter-Git-Ignore
  .gitignore
Labels: documentation, En cours, Prochaine version (urgent), Review

#23 R2-I19-Script
  french/script.rpy
Labels: En cours, Prochaine version (urgent), Review

#22 R2-I9-Credits
  french/script/credits.rpy
Labels: En cours, Prochaine version (urgent), Review

#26 R2-I17-Screens-HistoryScreen
  french/screens/dialogue_screens.rpy
  french/screens/game_menu.rpy
  french/screens/main_menu.rpy
  french/screens/other_screens.rpy
  french/screens/popup_screens.rpy
  french/screens/preferences.rpy
  french/screens/save_load.rpy
  french/screens/scroll/history_screen.rpy
Labels: En cours, Prochaine version (urgent), Review

#34 R2-I16-music_room.rpy
  french/music_room/music_room.rpy
Labels: En cours, Prochaine version (urgent), Review

#35 R2-I27-battle
  french/battle/battle.rpy
  french/battle/info.rpy
Labels: En cours, Prochaine version (urgent), Review

#37 R2-I11-outline shader
  french/effects/outline_shader.rpy
Labels: En cours, Prochaine version (urgent), Review

#39 R2-I10-augmentation_locations.rpy
  french/battle/core_files/augmentation_locations.rpy
Labels: En cours, Prochaine version (urgent), Review

#38 R2-I12-red_command_01.rpy
  french/exploratory/conv/red_command_01.rpy
Labels: En cours, Prochaine version (urgent), Review

#42 R2-I29-battleene files
  french/battle/ene_files/grimm_menagerie.rpy
  french/battle/ene_files/grimm_rcwater.rpy
  french/battle/ene_files/white_fang.rpy
Labels: En cours, Prochaine version (urgent), Review

#36 R2-I14-Translated Outback_01 and 02
  french/maps/outback_01.rpy
  french/maps/outback_02.rpy
Labels: À merge, Prochaine version (urgent)

#43 R2-I28-battlepcs-files
  french/battle/pcs_files/david.rpy
  french/battle/pcs_files/evelyn.rpy
  french/battle/pcs_files/guest_cards.rpy
  french/battle/pcs_files/jacqueline.rpy
  french/battle/pcs_files/penny.rpy
  french/battle/pcs_files/ruby.rpy
  french/battle/pcs_files/sienna_khan.rpy
Labels: En cours, Prochaine version (urgent), Review

#40 R2-I30-core files
  french/battle/core_files/dust_cores.rpy
  french/battle/core_files/player_cards.rpy
Labels: À merge, Prochaine version (urgent)

#41 R2-I15-maps/conv/ files
  french/maps/conv/evelyn_convs.rpy
  french/maps/conv/jack_convs.rpy
  french/maps/conv/maria_convs.rpy
  french/maps/conv/penny_convs.rpy
  french/maps/conv/ruby_convs.rpy
  french/maps/conv/sienna_khan.rpy
Labels: À merge, Prochaine version (urgent)

#44 R2-I32-screens/scroll sans history screen
  french/screens/scroll/calendar.rpy
  french/screens/scroll/dust_suit.rpy
  french/screens/scroll/hunt_allies.rpy
  french/screens/scroll/hunt_enemies.rpy
  french/screens/scroll/hunt_entities.rpy
  french/screens/scroll/hunt_events.rpy
  french/screens/scroll/hunt_locations.rpy
  french/screens/scroll/hunt_objects.rpy
  french/screens/scroll/inventory.rpy
  french/screens/scroll/profile_deck_screens.rpy
  french/screens/scroll/profiles.rpy
  french/screens/scroll/quest.rpy
  french/screens/scroll/quest_descriptions.rpy
  french/screens/scroll/scroll_main.rpy
Labels: En cours, Prochaine version (urgent), Review
